$(window).on('scroll',function(ev){
    if(document.body.scrollTop>230){
        $('#nav').addClass('sub');
        $('#aside').addClass('fixed');
    }else{
        $('#nav').removeClass('sub');
        $('#aside').removeClass('fixed');
    }
})
